apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: 640168457618.dkr.ecr.us-east-2.amazonaws.com/healthsync/notification-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: PG_HOST
          value: "postgresql"
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP
