apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-record-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-record
  template:
    metadata:
      labels:
        app: patient-record
    spec:
      containers:
      - name: patient-record
        image: 640168457618.dkr.ecr.us-east-2.amazonaws.com/healthsync/patient-record-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: PG_HOST
          value: "postgresql"
      imagePullSecrets:
      - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  selector:
    app: patient-record
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP